# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arcgisgeocode_wrappers", use_symbols = TRUE, package_name = "arcgisgeocode")

#' @usage NULL
#' @useDynLib arcgisgeocode, .registration = TRUE
NULL

as_esri_point_json <- function(x, sr) .Call(wrap__as_esri_point_json, x, sr)

create_records <- function(object_id, single_line, address, address2, address3, neighborhood, city, subregion, region, postal, postal_ext, country_code, location, sr, n) .Call(wrap__create_records, object_id, single_line, address, address2, address3, neighborhood, city, subregion, region, postal, postal_ext, country_code, location, sr, n)

parse_location_json <- function(x) .Call(wrap__parse_location_json, x)

parse_candidate_json <- function(x) .Call(wrap__parse_candidate_json, x)

is_iso3166 <- function(code) .Call(wrap__is_iso3166, code)

iso_3166_2 <- function() .Call(wrap__iso_3166_2)

iso_3166_3 <- function() .Call(wrap__iso_3166_3)

iso_3166_names <- function() .Call(wrap__iso_3166_names)

parse_custom_location_json_ <- function(x, to_fill) .Call(wrap__parse_custom_location_json_, x, to_fill)

parse_rev_geocode_resp <- function(resps) .Call(wrap__parse_rev_geocode_resp, resps)

parse_suggestions <- function(x) .Call(wrap__parse_suggestions, x)


# nolint end
