# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arcgeocode_wrappers", use_symbols = TRUE, package_name = "arcgeocode")

#' @docType package
#' @usage NULL
#' @useDynLib arcgeocode, .registration = TRUE
NULL

as_esri_point_json <- function(x, sr) .Call(wrap__as_esri_point_json, x, sr)

reverse_geocode_rs <- function(service_url, locations, crs, lang, for_storage, feature_type, location_type, preferred_label_values, `_token`) .Call(wrap__reverse_geocode_rs, service_url, locations, crs, lang, for_storage, feature_type, location_type, preferred_label_values, `_token`)

parse_rev_geocode_resp <- function(resps) .Call(wrap__parse_rev_geocode_resp, resps)

#' @export
is_iso3166 <- function(code) .Call(wrap__is_iso3166, code)

iso_3166_2 <- function() .Call(wrap__iso_3166_2)

iso_3166_3 <- function() .Call(wrap__iso_3166_3)

iso_3166_names <- function() .Call(wrap__iso_3166_names)


# nolint end
