# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arcgeocode_wrappers", use_symbols = TRUE, package_name = "arcgeocode")

#' @docType package
#' @usage NULL
#' @useDynLib arcgeocode, .registration = TRUE
NULL

sfc_point_to_esri_point <- function(pnts, sr) invisible(.Call(wrap__sfc_point_to_esri_point, pnts, sr))

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)


# nolint end
